# Generated by Django 4.2.24 on 2025-09-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='user',
            new_name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
