# Generated by Django 4.2.24 on 2025-09-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_rename_user_tasks_assigned_to_remove_tasks_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='grade',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('rejected', 'Rejected')], default='assigned', max_length=20),
        ),
    ]
